// <auto-generated />
using System;
using InfoTechLabProjeFabrikasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTechLabProjeFabrikasi.Migrations
{
    [DbContext(typeof(InfoTechLabContext))]
    [Migration("20230724101947_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Districk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Minucipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Temizlik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Tesisat"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Nakliyat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Özel Ders"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Tadilat"
                        });
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityCode = 1,
                            Name = "ADANA"
                        },
                        new
                        {
                            Id = 2,
                            CityCode = 2,
                            Name = "ADIYAMAN"
                        },
                        new
                        {
                            Id = 3,
                            CityCode = 3,
                            Name = "AFYONKARAHİSAR"
                        },
                        new
                        {
                            Id = 4,
                            CityCode = 4,
                            Name = "AĞRI"
                        },
                        new
                        {
                            Id = 5,
                            CityCode = 5,
                            Name = "AMASYA"
                        },
                        new
                        {
                            Id = 6,
                            CityCode = 6,
                            Name = "ANKARA"
                        },
                        new
                        {
                            Id = 7,
                            CityCode = 7,
                            Name = "ANTALYA"
                        },
                        new
                        {
                            Id = 8,
                            CityCode = 8,
                            Name = "ARTVİN"
                        },
                        new
                        {
                            Id = 9,
                            CityCode = 9,
                            Name = "AYDIN"
                        },
                        new
                        {
                            Id = 10,
                            CityCode = 10,
                            Name = "BALIKESİR"
                        },
                        new
                        {
                            Id = 11,
                            CityCode = 11,
                            Name = "BİLECİK"
                        },
                        new
                        {
                            Id = 12,
                            CityCode = 12,
                            Name = "BİNGÖL"
                        },
                        new
                        {
                            Id = 13,
                            CityCode = 13,
                            Name = "BİTLİS"
                        },
                        new
                        {
                            Id = 14,
                            CityCode = 14,
                            Name = "BOLU"
                        },
                        new
                        {
                            Id = 15,
                            CityCode = 15,
                            Name = "BURDUR"
                        },
                        new
                        {
                            Id = 16,
                            CityCode = 16,
                            Name = "BURSA"
                        },
                        new
                        {
                            Id = 17,
                            CityCode = 17,
                            Name = "ÇANAKKALE"
                        },
                        new
                        {
                            Id = 18,
                            CityCode = 18,
                            Name = "ÇANKIRI"
                        },
                        new
                        {
                            Id = 19,
                            CityCode = 19,
                            Name = "ÇORUM"
                        },
                        new
                        {
                            Id = 20,
                            CityCode = 20,
                            Name = "DENİZLİ"
                        },
                        new
                        {
                            Id = 21,
                            CityCode = 21,
                            Name = "DİYARBAKIR"
                        },
                        new
                        {
                            Id = 22,
                            CityCode = 22,
                            Name = "EDİRNE"
                        },
                        new
                        {
                            Id = 23,
                            CityCode = 23,
                            Name = "ELAZIĞ"
                        },
                        new
                        {
                            Id = 24,
                            CityCode = 24,
                            Name = "ERZİNCAN"
                        },
                        new
                        {
                            Id = 25,
                            CityCode = 25,
                            Name = "ERZURUM"
                        },
                        new
                        {
                            Id = 26,
                            CityCode = 26,
                            Name = "ESKİŞEHİR"
                        },
                        new
                        {
                            Id = 27,
                            CityCode = 27,
                            Name = "GAZİANTEP"
                        },
                        new
                        {
                            Id = 28,
                            CityCode = 28,
                            Name = "GİRESUN"
                        },
                        new
                        {
                            Id = 29,
                            CityCode = 29,
                            Name = "GÜMÜŞHANE"
                        },
                        new
                        {
                            Id = 30,
                            CityCode = 30,
                            Name = "HAKKARİ"
                        },
                        new
                        {
                            Id = 31,
                            CityCode = 31,
                            Name = "HATAY"
                        },
                        new
                        {
                            Id = 32,
                            CityCode = 32,
                            Name = "ISPARTA"
                        },
                        new
                        {
                            Id = 33,
                            CityCode = 33,
                            Name = "MERSİN"
                        },
                        new
                        {
                            Id = 34,
                            CityCode = 34,
                            Name = "İSTANBUL"
                        },
                        new
                        {
                            Id = 35,
                            CityCode = 35,
                            Name = "İZMİR"
                        },
                        new
                        {
                            Id = 36,
                            CityCode = 36,
                            Name = "KARS"
                        },
                        new
                        {
                            Id = 37,
                            CityCode = 37,
                            Name = "KASTAMONU"
                        },
                        new
                        {
                            Id = 38,
                            CityCode = 38,
                            Name = "KAYSERİ"
                        },
                        new
                        {
                            Id = 39,
                            CityCode = 39,
                            Name = "KIRKLARELİ"
                        },
                        new
                        {
                            Id = 40,
                            CityCode = 40,
                            Name = "KIRŞEHİR"
                        },
                        new
                        {
                            Id = 41,
                            CityCode = 41,
                            Name = "KOCAELİ"
                        },
                        new
                        {
                            Id = 42,
                            CityCode = 42,
                            Name = "KONYA"
                        },
                        new
                        {
                            Id = 43,
                            CityCode = 43,
                            Name = "KÜTAHYA"
                        },
                        new
                        {
                            Id = 44,
                            CityCode = 44,
                            Name = "MALATYA"
                        },
                        new
                        {
                            Id = 45,
                            CityCode = 45,
                            Name = "MANİSA"
                        },
                        new
                        {
                            Id = 46,
                            CityCode = 46,
                            Name = "KAHRAMANMARAŞ"
                        },
                        new
                        {
                            Id = 47,
                            CityCode = 47,
                            Name = "MARDİN"
                        },
                        new
                        {
                            Id = 48,
                            CityCode = 48,
                            Name = "MUĞLA"
                        },
                        new
                        {
                            Id = 49,
                            CityCode = 49,
                            Name = "MUŞ"
                        },
                        new
                        {
                            Id = 50,
                            CityCode = 50,
                            Name = "NEVŞEHİR"
                        },
                        new
                        {
                            Id = 51,
                            CityCode = 51,
                            Name = "NİĞDE"
                        },
                        new
                        {
                            Id = 52,
                            CityCode = 52,
                            Name = "ORDU"
                        },
                        new
                        {
                            Id = 53,
                            CityCode = 53,
                            Name = "RİZE"
                        },
                        new
                        {
                            Id = 54,
                            CityCode = 54,
                            Name = "SAKARYA"
                        },
                        new
                        {
                            Id = 55,
                            CityCode = 55,
                            Name = "SAMSUN"
                        },
                        new
                        {
                            Id = 56,
                            CityCode = 56,
                            Name = "SİİRT"
                        },
                        new
                        {
                            Id = 57,
                            CityCode = 57,
                            Name = "SİNOP"
                        },
                        new
                        {
                            Id = 58,
                            CityCode = 58,
                            Name = "SİVAS"
                        },
                        new
                        {
                            Id = 59,
                            CityCode = 59,
                            Name = "TEKİRDAĞ"
                        },
                        new
                        {
                            Id = 60,
                            CityCode = 60,
                            Name = "TOKAT"
                        },
                        new
                        {
                            Id = 61,
                            CityCode = 61,
                            Name = "TRABZON"
                        },
                        new
                        {
                            Id = 62,
                            CityCode = 62,
                            Name = "TUNCELİ"
                        },
                        new
                        {
                            Id = 63,
                            CityCode = 63,
                            Name = "ŞANLIURFA"
                        },
                        new
                        {
                            Id = 64,
                            CityCode = 64,
                            Name = "UŞAK"
                        },
                        new
                        {
                            Id = 65,
                            CityCode = 65,
                            Name = "VAN"
                        },
                        new
                        {
                            Id = 66,
                            CityCode = 66,
                            Name = "YOZGAT"
                        },
                        new
                        {
                            Id = 67,
                            CityCode = 67,
                            Name = "ZONGULDAK"
                        },
                        new
                        {
                            Id = 68,
                            CityCode = 68,
                            Name = "AKSARAY"
                        },
                        new
                        {
                            Id = 69,
                            CityCode = 69,
                            Name = "BAYBURT"
                        },
                        new
                        {
                            Id = 70,
                            CityCode = 70,
                            Name = "KARAMAN"
                        },
                        new
                        {
                            Id = 71,
                            CityCode = 71,
                            Name = "KIRIKKALE"
                        },
                        new
                        {
                            Id = 72,
                            CityCode = 72,
                            Name = "BATMAN"
                        },
                        new
                        {
                            Id = 73,
                            CityCode = 73,
                            Name = "ŞIRNAK"
                        },
                        new
                        {
                            Id = 74,
                            CityCode = 74,
                            Name = "BARTIN"
                        },
                        new
                        {
                            Id = 75,
                            CityCode = 75,
                            Name = "ARDAHAN"
                        },
                        new
                        {
                            Id = 76,
                            CityCode = 76,
                            Name = "IĞDIR"
                        },
                        new
                        {
                            Id = 77,
                            CityCode = 77,
                            Name = "YALOVA"
                        },
                        new
                        {
                            Id = 78,
                            CityCode = 78,
                            Name = "KARABÜK"
                        },
                        new
                        {
                            Id = 79,
                            CityCode = 79,
                            Name = "KİLİS"
                        },
                        new
                        {
                            Id = 80,
                            CityCode = 80,
                            Name = "OSMANİYE"
                        },
                        new
                        {
                            Id = 81,
                            CityCode = 81,
                            Name = "DÜZCE"
                        });
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EMail = "zeynepbilgic@gmail.com",
                            Name = "Zeynep Bilgiç",
                            PhoneNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            EMail = "mehmettan@gmail.com",
                            Name = "Mehmet Tan",
                            PhoneNumber = 0
                        });
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EMail = "yusufali@gmail.com",
                            MiddleName = "Ali",
                            Name = "Yusuf",
                            PhoneNumber = "05553462133",
                            ServiceArea = "Su Tesisatı",
                            Surname = "Kurt"
                        },
                        new
                        {
                            Id = 2,
                            EMail = "g.muratkaraca@gmail.com",
                            MiddleName = "Murat",
                            Name = "Gökhan",
                            PhoneNumber = "05553462133",
                            ServiceArea = "Kombi Tesisatı",
                            Surname = "Karaca"
                        },
                        new
                        {
                            Id = 3,
                            EMail = "a.cankısa@gmail.com",
                            MiddleName = "",
                            Name = "Emir",
                            PhoneNumber = "05323698520",
                            ServiceArea = "Kombi Tesisatı",
                            Surname = "Alioğlu"
                        },
                        new
                        {
                            Id = 4,
                            EMail = "yasinnnuroglu@gmail.com",
                            MiddleName = "",
                            Name = "Yasin",
                            PhoneNumber = "05362314578",
                            ServiceArea = "Su Tesisatı",
                            Surname = "Nuroğlu"
                        },
                        new
                        {
                            Id = 5,
                            EMail = "m.rıza@gmail.com",
                            MiddleName = "Rıza",
                            Name = "Mustafa",
                            PhoneNumber = "05356231459",
                            ServiceArea = "Ev Nakliyat",
                            Surname = "Yurttaş"
                        },
                        new
                        {
                            Id = 6,
                            EMail = "eminkaraoglu@gmail.com",
                            MiddleName = "",
                            Name = "Emin",
                            PhoneNumber = "05355632147",
                            ServiceArea = "Ev Nakliyat",
                            Surname = "Karaoğlu"
                        },
                        new
                        {
                            Id = 7,
                            EMail = "a.cankısa@gmail.com",
                            MiddleName = "Can",
                            Name = "Abdullah",
                            PhoneNumber = "05348963214",
                            ServiceArea = "Ev Nakliyat",
                            Surname = "Kısa"
                        },
                        new
                        {
                            Id = 8,
                            EMail = "ıhsanuzun@gmail.com",
                            MiddleName = "",
                            Name = "İhsan",
                            PhoneNumber = "05389632314",
                            ServiceArea = "Ev Boya Tadilat",
                            Surname = "Uzun"
                        },
                        new
                        {
                            Id = 9,
                            EMail = "n.rızabalaban@gmail.com",
                            MiddleName = "Rıza",
                            Name = "Nuri",
                            PhoneNumber = "05321369654",
                            ServiceArea = "Ev Boya Tadilat",
                            Surname = "Balaban"
                        },
                        new
                        {
                            Id = 10,
                            EMail = "fehmigursoy@gmail.com",
                            MiddleName = "",
                            Name = "Fehmi",
                            PhoneNumber = "05367894512",
                            ServiceArea = "Ev Banyo Tadilat",
                            Surname = "Gürsoy"
                        },
                        new
                        {
                            Id = 11,
                            EMail = "haydardirican@gmail.com",
                            MiddleName = "",
                            Name = "Haydar",
                            PhoneNumber = "05346987436",
                            ServiceArea = "Ev Banyo Tadilat",
                            Surname = "Dirican"
                        },
                        new
                        {
                            Id = 12,
                            EMail = "fatmaparlak@gmail.com",
                            MiddleName = "",
                            Name = "Fatma",
                            PhoneNumber = "05342365897",
                            ServiceArea = "Ev Temizlik",
                            Surname = "Parlak"
                        },
                        new
                        {
                            Id = 13,
                            EMail = "aysenurkorkmaz@gmail.com",
                            MiddleName = "Nur",
                            Name = "Ayşe",
                            PhoneNumber = "05325632147",
                            ServiceArea = "Ev Temizlik",
                            Surname = "Korkmaz"
                        },
                        new
                        {
                            Id = 14,
                            EMail = "esrahaktan@gmail.com",
                            MiddleName = "",
                            Name = "Esra",
                            PhoneNumber = "05378963215",
                            ServiceArea = "Ev Temizlik",
                            Surname = "Haktan"
                        },
                        new
                        {
                            Id = 15,
                            EMail = "yusufali@gmail.com",
                            MiddleName = "Ali",
                            Name = "Yusuf",
                            PhoneNumber = "05553462133",
                            ServiceArea = "Su Tesisatı",
                            Surname = "Kurt"
                        },
                        new
                        {
                            Id = 16,
                            EMail = "leylakara@gmail.com",
                            MiddleName = "",
                            Name = "Leyla",
                            PhoneNumber = "05478562314",
                            ServiceArea = "Matematik Özel Ders",
                            Surname = "Kara"
                        },
                        new
                        {
                            Id = 17,
                            EMail = "ayhandonmez@gmail.com",
                            MiddleName = "",
                            Name = "Ayhan",
                            PhoneNumber = "05362696321",
                            ServiceArea = "Matematik Özel Ders",
                            Surname = "Dönmez"
                        },
                        new
                        {
                            Id = 18,
                            EMail = "ebruyurtseven@gmail.com",
                            MiddleName = "",
                            Name = "Ebru",
                            PhoneNumber = "05562314569",
                            ServiceArea = "Matematik Özel Ders",
                            Surname = "Yurtseven"
                        },
                        new
                        {
                            Id = 19,
                            EMail = "nurdandertli@gmail.com",
                            MiddleName = "",
                            Name = "Nurdan",
                            PhoneNumber = "05312659874",
                            ServiceArea = "Fizik Özel Ders",
                            Surname = "Dertli"
                        },
                        new
                        {
                            Id = 20,
                            EMail = "aslısever@gmail.com",
                            MiddleName = "",
                            Name = "Aslı",
                            PhoneNumber = "05326987546",
                            ServiceArea = "Fizik Özel Ders",
                            Surname = "Sever"
                        },
                        new
                        {
                            Id = 21,
                            EMail = "muratkaraman@gmail.com",
                            MiddleName = "",
                            Name = "Murat",
                            PhoneNumber = "05369875632",
                            ServiceArea = "Türkçe Özel Ders",
                            Surname = "Karaman"
                        },
                        new
                        {
                            Id = 22,
                            EMail = "nilgunvatansever@gmail.com",
                            MiddleName = "",
                            Name = "Nilgün",
                            PhoneNumber = "05336952314",
                            ServiceArea = "Türkçe Özel Ders",
                            Surname = "Vatansever"
                        },
                        new
                        {
                            Id = 23,
                            EMail = "n.ayseyılmaz@gmail.com",
                            MiddleName = "Ayşe",
                            Name = "Nalan",
                            PhoneNumber = "05426312369",
                            ServiceArea = "İngilizce Özel Ders",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 24,
                            EMail = "alikemalcandan@gmail.com",
                            MiddleName = "Kemal",
                            Name = "Ali",
                            PhoneNumber = "05352698741",
                            ServiceArea = "İngilizce Özel Ders",
                            Surname = "Candan"
                        });
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Address", b =>
                {
                    b.HasOne("InfoTechLabProjeFabrikasi.Data.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechLabProjeFabrikasi.Data.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId");

                    b.HasOne("InfoTechLabProjeFabrikasi.Data.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Platform", b =>
                {
                    b.HasOne("InfoTechLabProjeFabrikasi.Data.Category", "Category")
                        .WithMany("Platforms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechLabProjeFabrikasi.Data.Customer", "Customer")
                        .WithMany("Platforms")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoTechLabProjeFabrikasi.Data.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Category", b =>
                {
                    b.Navigation("Platforms");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("InfoTechLabProjeFabrikasi.Data.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
